services:
  - type: web
    name: hmplanningpoker
    runtime: docker
    plan: starter
    healthCheckPath: /healthz
    autoDeploy: true
    disk:
      name: hmpp-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
